### ISSUE TITLE
First line of changelog section is always considered a summary

### ISSUE THREAD

**Issue by coagulant** [AllMyChanges/original.allmychanges.com#16]
![Screenshot](http://f.cl.ly/items/1q070i1H3W3U083R2X0o/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202013-10-07%20%D0%B2%2020.43.47.png)

It's not always the case, sometimes it's only a list.
https://github.com/coagulant/coveralls-python/blob/master/CHANGELOG.rst

**Comment by svetlyak40wt** [comment]
Actually, what you described is intended behaviour. What you get is a bug in the parser.

**Comment by svetlyak40wt** [comment]
Already fixed.

**Comment by coagulant** [comment]
http://allmychanges.com/u/coagulant/python/coveralls-python/
First bullet list item lacks a badge:

![](http://cl.ly/image/0b2l0F2O1V1p/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202014-09-21%20%D0%B2%2020.46.32.png)

**Comment by svetlyak40wt** [comment]
Well, it is fixed in the new parser only. If you want to check how changelog in new version will work, add `?code_version=v2` to the url: http://allmychanges.com/u/coagulant/python/coveralls-python/?code_version=v2
