### ISSUE TITLE
На странице «Ничего не найдено» в шапке ссылки на логин вместо профиля

### ISSUE THREAD

**Issue by h4** [AllMyChanges/original.allmychanges.com#20]
Например, такой запрос http://allmychanges.com/search/?q=handlebars

![2014-11-11 16-52-01 allmychanges com](https://cloud.githubusercontent.com/assets/430023/4993748/13934b46-69c3-11e4-8460-7fa871a726b9.png)

**Comment by svetlyak40wt** [comment]
О, спасибо! Поправлю в ближайшем релизе!
