### ISSUE TITLE
Unicode problem (?)

### ISSUE THREAD

**Issue by davidmz** [AllMyChanges/original.allmychanges.com#25]
Странно отображается многоточие на [этой странице](http://allmychanges.com/p/new/?url=https%3A%2F%2Fgithub.com%2Fdavidmz%2Fipgeobase):

![2014-12-29 13-24-49 allmychanges com - google chrome](https://cloud.githubusercontent.com/assets/132120/5567862/610250a0-8f5e-11e4-988a-311dda9b8c5d.png)

Файл: https://github.com/davidmz/ipgeobase/blob/master/CHANGELOG.md

**Comment by svetlyak40wt** [comment]
Большое спасибо, Давид!

Там действительно был недочет в цепочке парсера — терялась информация о кодировке. Сейчас всё исправил.
