### ISSUE TITLE
Bulk import github stared projects

### ISSUE THREAD

**Issue by netantho** [AllMyChanges/original.allmychanges.com#26]
Feature request: Import all the stared projects from a user's github profile. Find changelogs in these projects to track them.

**Comment by bessarabov** [comment]
I did a script that does exacly that — https://github.com/bessarabov/App-AllMyChangesUtils Maybe it will suit your needs.

**Comment by svetlyak40wt** [comment]
By the way, @bessarabov could you please lowercase namespace and name in your utility's output?

**Comment by netantho** [comment]
Sorry for the delay, I tried and it does what I wanted, nice! :)
