### ISSUE TITLE
Feature request: list of tracked projects

### ISSUE THREAD

**Issue by netantho** [AllMyChanges/original.allmychanges.com#27]
(Disclaimer: sorry if such page already exists and I just don't manage to find it)

It would be great to have a page (linked from the top menu) to list the projects the logged in user is tracked, and give them the ability to quickly untrack some projects.

Let me know if it's something you think would be useful, I could probably implement it.

**Comment by svetlyak40wt** [comment]
Anthony, you are not along in the desire to see full list of tracked packages. I'm planning to implement this feature in future.

By the way, probably it is even more useful than http://allmychanges.com/digest/ page? What do you think?

**Comment by netantho** [comment]
Hi,

The digest page is still useful I guess for people you don't read their emails or don't want emails.
Buttons to untrack packages there could be useful as well though.

Can you give me 2-3 weeks max to make progress on it? I would love to contribute a bit to this project.

**Comment by netantho** [comment]
@svetlyak40wt Is this github repo up to date?
I don't see the releases mentioned on https://allmychanges.com/p/web/allmychanges/

**Comment by svetlyak40wt** [comment]
No, the code in this repo is outdates and only contains changes we made for Django Dash hackaton in 2013. After that, I transferred all code to my private repository and all development continued there.

But issues in this repository still could be used for bugreporting.

**Comment by Wtower** [comment]
Hi @svetlyak40wt , first congrats for the nice project. We met on twitter already (@gckarak).

I think too that this feature would be nice to have, but sure nothing that we can't live with.

**Comment by svetlyak40wt** [comment]
Oh, guys. I'm so sorry, but I forgot to close this issue. This feature was implemented in most recent release: https://allmychanges.com/p/web/allmychanges/#0.25.0

Click on your username in the top right screen's corner and select "Track list" item.

**Comment by Wtower** [comment]
Argh, missed it. Great!
