### ISSUE TITLE
java/Guava: No space left on device

### ISSUE THREAD

**Issue by valery1707** [AllMyChanges/original.allmychanges.com#34]
Для пакета  [java/Guava](https://allmychanges.com/p/java/guava/) система показывает далеко не все версии, а так же ошибку `Bad status_code from git clone: -13. Git's stderr: Cloning into '/tmp/allmychanges/tmp2eNrT8'... fatal: write error: No space left on device`

**Comment by svetlyak40wt** [comment]
Спасибо, исправили.

**Comment by valery1707** [comment]
По ссылке всё еще показывается ошибка, и версий не стало больше.

**Comment by svetlyak40wt** [comment]
Валерий, ты прав, ошибка всё еще показывается, потому что я забыл снять с паузы обновление этого пакета, когда решилась проблема с место м на диске. Сейчас снял.

Впрочем, похоже с ним есть еще одна проблема — по какой-то причине блохо отрабатывает сборщик версий по коммит-мессаджам, ведь тегов в репозитории куда больше.
