### ISSUE TITLE
Post the changes on slack integration

### ISSUE THREAD

**Issue by danielgomezrico** [AllMyChanges/original.allmychanges.com#43]
The actual slack integration just print 

```
Look, new version of clojure/icepick was found: 3.2.0
```

Will be cool to see all the changelog for that version too.

**Comment by svetlyak40wt** [comment]
It is not always possible to overcome Slack's markup limitations. In general case, release notes can have any HTML markup including images other elements. I don't know way how to insert such content into the slack.

Do you have any ideas?

**Comment by danielgomezrico** [comment]
I sent a help request to slack to see if this is posible

**Comment by svetlyak40wt** [comment]
Ok, update this issue if you'll find out a way to post html into the slack. May be the have some sort of converter which will do the job.

**Comment by danielgomezrico** [comment]
@svetlyak40wt what about using tools like this https://github.com/domchristie/to-markdown?

**Comment by svetlyak40wt** [comment]
This could be the option. But I have to sind similar library for Python or
to wrap https://github.com/domchristie/to-markdown into a microservice.
Probably, will do some investigations on this holidays.

On Fri, Feb 26, 2016 at 6:53 PM, Daniel Gomez Rico <notifications@github.com

> wrote:
> 
> @svetlyak40wt https://github.com/svetlyak40wt what about using tools
> like this https://github.com/domchristie/to-markdown?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AllMyChanges/allmychanges.com/issues/43#issuecomment-189336063
> .

## 

Alexander Artemenko (a.k.a. Svetlyak 40wt)
Blog: http://dev.svetlyak.ru
Photos: http://svetlyak.ru
Jabber: svetlyak.40wt@gmail.com

**Comment by danielgomezrico** [comment]
:+1:

**Comment by dpwiz** [comment]
I guess that was implemented recently... Now I need a checkbox to turn it back into abbreviated form.

This is not how a usable changelog looks: https://imgur.com/pKEEqz7

**Comment by svetlyak40wt** [comment]
@wiz sure, a adding settings will be useful. But in this case another "issue" should be created – we need to reformat markdown links into the format which Slack understands.

**Comment by danielgomezrico** [comment]
Slack support click "here for more" to enable autocollapsed posts, not sure if that works for web hooks but some integrations post like 4 lines and "click here for more" and then expands.

**Comment by svetlyak40wt** [comment]
Right. This uses "attachments" under the hood. But I've checked this feature and attachments dont support Slack's markup – only the links. No "bold", no code snippets. In this case, attachments looks worse than plain message without "here for more" link.

If you noticed, I've released new version of AllMyChanges today. It fixed most markup issues for Slack integration.

**Comment by svetlyak40wt** [comment]
@wiz do you really want an option to return back short notifications that some version was released? Or current version with fixed markup is OK?

**Comment by dpwiz** [comment]
> Or current version with fixed markup is OK?

Some more fixes needed https://imgur.com/vDlDIuY

I'll wait for more samples now and report back :smile:

**Comment by svetlyak40wt** [comment]
BTW, Slack's support replied me with a way how to turn on markup support inside attachements. Probably, I'll try to switch to them soon if will have a free time.

**Comment by svetlyak40wt** [comment]
About images, I need to expreiment with them. Slack's markup is very restricted and took only some elements from markdown. Probably the only way to insert images into the text, is to insert it url as is.

**Comment by svetlyak40wt** [comment]
BTW, I've fixed slack notification representation to use attachments now they should be more usable.

**Comment by danielgomezrico** [comment]
@svetlyak40wt on which version?

**Comment by svetlyak40wt** [comment]
@danielgomezrico  currently, AllMyChanges should send all notifications to slack as attachments. But there is still a problem with embedding images because they aren't supported inside attachments.

**Comment by dpwiz** [comment]
Inline link markup is a little wonky... https://imgur.com/kXy3PAC

**Comment by svetlyak40wt** [comment]
Seems, by stupid regex don't like spaces in the link's text. Will fix it. Thank you, @wiz!

**Comment by dpwiz** [comment]
https://imgur.com/g13AEho

Perhaps more readability could be gained by extracting links to "footnotes"?

**Comment by svetlyak40wt** [comment]
@wiz these links should be real links in Slack. Probably my markup converter wasn't able to handle them. Thank you.

**Comment by dpwiz** [comment]
So far, so good...

**Comment by svetlyak40wt** [comment]
Well, I'll close this issue. If you'll encounter other problems, please, open separate issues.
