### ISSUE TITLE
Recognize “TBA” as equivalent to “Unreleased”

### ISSUE THREAD

**Issue by vfaronov** [AllMyChanges/original.allmychanges.com#52]
AllMyChanges.com has picked up [python/pylint](https://allmychanges.com/p/python/pylint/) 2.0 from its [changelog](https://github.com/PyCQA/pylint/blob/0f240589a39d145f207d7e9cadeb088eb59e365d/ChangeLog), where it is listed as “Release date: tba”. AllMyChanges.com should recognize this as equivalent to “Unreleased”.

**Comment by svetlyak40wt** [comment]
Thanks, tuned the project.
