### ISSUE TITLE
Namespaces are not case-folded in the catalogue

### ISSUE THREAD

**Issue by vfaronov** [AllMyChanges/original.allmychanges.com#55]
The namespaces marked on this screenshot are actually the same:

![allmychanges-namespaces](https://cloud.githubusercontent.com/assets/300211/17154126/588980a2-5388-11e6-80f5-dc68fb955b1d.png)

**Comment by svetlyak40wt** [comment]
Thanks for this issue. I've normalized namespaces and fixed code to make it impossible to have few namespaces with difference in case.
