### ISSUE TITLE
HTTP 500 for RSS link.

### ISSUE THREAD

**Issue by IRus** [AllMyChanges/original.allmychanges.com#57]
Hi. I just login to service via github, follow few projects and try to add RSS feed to reader. But unfortunately i constantly get `Server Error (500)`.

**Comment by svetlyak40wt** [comment]
Thank you for the report, Ruslan.

There was an issue with the database. I've resolved it. Please, check again if 500 error for rss link is gone.

**Comment by IRus** [comment]
@svetlyak40wt Now it works, thank you!
