### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by williamdes** [AllMyChanges/original.allmychanges.com#62]
See : [Faq](https://allmychanges.com/help/faq/)

> There is a good description at KeepAChangelog site. Also, there is a SemanticReleaseNotes proposal which is aimed to provide us with a new textual format for release notes.

[SemanticReleaseNotes](http://www.semanticreleasenotes.org/) is a broken link.

I hope I posted this issue in the correct place.

**Comment by williamdes** [comment]
[Docs](https://allmychanges.com/help/faq/index) » FAQ  is a broken link.

And ```<a href=”#feedback”>feedback form</a>``` is displayed in plain text.

**Comment by williamdes** [comment]
@svetlyak40wt ?

**Comment by svetlyak40wt** [comment]
Hi!

The good catch seems SemanticReleaseNotes site is gone.

**Comment by svetlyak40wt** [comment]
I'll fixe these links soon.

**Comment by williamdes** [comment]
Thank you :)

**Comment by williamdes** [comment]
@svetlyak40wt 
https://allmychanges.com/help/tools
~~`View Changelog` has no effect, tested with latest Mozilla and Chrome.~~

**Comment by svetlyak40wt** [comment]
@williamdes I've tested it right now in Chrome, and it works.

Did'you drag it onto the bookmarks bar?

**Comment by williamdes** [comment]
@svetlyak40wt The link works, I was trying to click the link :laughing:

**Comment by williamdes** [comment]
@svetlyak40wt Website is down from more than 2 days
What is going on ?

**Comment by svetlyak40wt** [comment]
Hi, @williamdes thanks for the alert.

Project a little bit abandoned nowadays, because it was noncommercial and made just for fun.

I've rebuilt the documentation and fixed the link, and resurrected the docker container where it is running.

**Comment by williamdes** [comment]
@svetlyak40wt It is a very helpful project, I need it :)
You forgot the ```<a href=”#feedback”>feedback form</a>``` in FAQ

**Comment by williamdes** [comment]
And the Docs link
