### ISSUE TITLE
New GitHub release is not visible

### ISSUE THREAD

**Issue by lrozenblyum** [AllMyChanges/original.allmychanges.com#66]
The release 0.3 of https://github.com/lrozenblyum/chess/releases was published yesterday to GitHub 
![image](https://user-images.githubusercontent.com/1285898/50610909-30c09700-0edd-11e9-9d67-906cf3c91543.png)

However it's still invisible in AllMyChanges:
![image](https://user-images.githubusercontent.com/1285898/50610834-01118f00-0edd-11e9-96fd-904bdadd9b56.png)

**Comment by lrozenblyum** [comment]
The new release appeared on site. Maybe it was a temporary issue

**Comment by svetlyak40wt** [comment]
Yes, task queue stuck. I've restarted it and now everything should be fine.

Thank you for the report @lrozenblyum! 👍
