### ISSUE TITLE
Process GitHub Releases, if project manintainers use it

### ISSUE THREAD

**Issue by svetlyak40wt** [AllMyChanges/original.allmychanges.com#9]
For example, these packages use GitHub Releases:
- https://github.com/bem/bem-tools/releases
- https://github.com/purescript/purescript/releases
- https://github.com/mongodb/mongo-c-driver/releases

**Comment by chibisov** [comment]
Было бы удобно, если бы наш парсер формировал модель данных как в гитхабоских релизах. Таким образом можно зайти на сайт, распарсить свой changelog.md и экспортнуть это всё в releases. Ну и наоборот - по releases сформировать changelog.md

**Comment by outcoldman** [comment]
I just used url to releases instead of link to github project, looks like it is working https://allmychanges.com/p/c/MongoDB%20driver%20for%20C/

**Comment by svetlyak40wt** [comment]
@outcoldman hmm, it worked for MongoDB driver, but does not work for bem-tools: https://allmychanges.com/p/new/?url=https%3A%2F%2Fgithub.com%2Fbem%2Fbem-tools%2Freleases

I think, we need to support GitHub releases natively. The easiest way here is to add another kind of downloader which will be able to process github releases.

I think, we should use this issue to collect a list of repositories, which use GitHub Releases. This way it will be easier to implement and test this feature.

**Comment by svetlyak40wt** [comment]
https://github.com/purescript/purescript/releases

**Comment by svetlyak40wt** [comment]
I release a new 0.26.0 version of AllMyChanges with native support of GitHub's Releases.

All projects, which are already in the database and support GitHub's releases will be converted to support this new downloader manually to ensure that we won't break them.

**Comment by svetlyak40wt** [comment]
For newly added URLs, our service discovers automatically if project's maintainers use GitHub's release notes.
